package com.blackwell.level_01;

public class Problem_002 {
    public static final int ID = 2;
    public static final String NAME = "Even Fibonacci numbers";
    public static final String INFO = "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n" +
            "\n" + "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n" +
            "\n" + "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";

    public Problem_002() {
        int sum=0;
        int privNum=1,privPrivNum=1;
        for(int i = 2;i< 4_000_000;i=privNum+privPrivNum){
            if (i%2 == 0)
                sum+=i;
            privPrivNum=privNum;
            privNum=i;
        }
        System.out.println(sum);
    }
}
