package Level_01;

import java.util.Scanner;

public class LevelControl_01 {
    public LevelControl_01() {
        System.out.println("If you want to get full list enter 0.\nEnter Problem number: ");
        Scanner in = new Scanner(System.in);
        int ProblemNum=in.nextInt();
        switch (ProblemNum){
            case 0:
                PrintFullList();
                break;
            case 1:


        }
    }
    private void PrintFullList(){
        for (int i=1;i<=25;++i)
            System.out.println(ProblemNames[i]);

        System.out.println("Enter ProblemNum to get full info");
        Scanner in = new Scanner(System.in);
        int ProblemNum=in.nextInt();
        System.out.println(ProblemInfo[ProblemNum]);
    }

    public String[] getProblemNames() {
        return ProblemNames;
    }

    private String[] ProblemNames={
            "001. Multiples of 3 and 5",
            "002. Even Fibonacci numbers",
            "003. Largest prime factor",
            "004. Largest palindrome product"
    };
    private String[] ProblemInfo={
            "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.\n" +
                    "\n" +
                    "Find the sum of all the multiples of 3 or 5 below 1000.",
            "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n" +
                    "\n" +
                    "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n" +
                    "\n" +
                    "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.",
            "The prime factors of 13195 are 5, 7, 13 and 29.\n" +
                    "\n" +
                    "What is the largest prime factor of the number 600851475143 ?",
            "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.\n" +
                    "\n" +
                    "Find the largest palindrome made from the product of two 3-digit numbers."
    };
}
